#!/usr/bin/env bash
# Install HAProxy

sudo apt-get update
sudo apt-get install -y haproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 470655-web-01:80 check
    server web-02 470655-web-02:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy management via init script
sudo systemctl enable haproxy

# Update /etc/hosts with the correct hostnames
sudo sed -i '/470655-web-01/c\470655-web-01   100.26.214.182' /etc/hosts
sudo sed -i '/470655-web-02/c\470655-web-02   54.162.5.131' /etc/hosts
