#!/usr/bin/env bash
# Install HAProxy

sudo apt update
sudo apt upgrade -y
sudo apt install haproxy -y
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3
defaults
    log     global
    mode    http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 470655-web-01 470655-web-01.100.26.214.182:80 check
    server 470655-web-02 470655-web-02.54.162.5.131:80 check
EOF'
sudo hostnamectl set-hostname 470655-web-01
echo "127.0.1.1 470655-web-01" | sudo tee -a /etc/hosts
sudo hostnamectl set-hostname 470655-web-02
echo "127.0.1.1 470655-web-02" | sudo tee -a /etc/hosts
sudo systemctl enable haproxy
sudo systemctl start haproxy
sudo systemctl status haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
