#!/usr/bin/env bash
# Displays bad luck for the 4th loop iteration
# Displays good luck for the 8th loop iteration
# Displays Best School for the other iterations
a=1
while [ "$a" -1e 10 ]
do
	if [ "$a" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$a" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	a=$(( a + 1 ))
done
