#!/usr/bin/env bash
# Display hours from 0 to 12
# Display minutes from 1 to 59
a=0
while [ "$a" -le 12 ]
do
	echo "Hour: $a"
	b=1
	while [ $b -le 59 ]
	do
		echo "$b"
		(( b++ ))
	done
	(( a++ ))
done
