#!/usr/bin/env bash

#Define the name of the private key
private_key="school"

#Define the number of bits
bits=4096

#Define the passphrase
passphrase="betty"

#Generate RSA key pair
ssh-keygen -t rsa -b $bits -f ~/.ssh/$private_key -N $passphrase

#Display success message
echo "RSA key pair generated successfully."
